"""add missing user columns

Revision ID: 43fa6b51c375
Revises: a795661b7c7d
Create Date: 2026-07-19 20:06:44.418277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fa6b51c375'
down_revision = 'a795661b7c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revision_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previous_rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('calendar_feed_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('push_notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('calendar_feed_token')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('previous_rejection_reason')
        batch_op.drop_column('revision_count')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
